# Generated by Django 4.2.4 on 2023-09-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('new', 'New Product'), ('refurbished', 'Refurbished Product')], default='new', max_length=20)),
                ('refurbished_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent Quality'), ('good', 'Good Quality'), ('average', 'Average Quality')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
