# Generated by Django 4.2.4 on 2023-09-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='refurbished_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'excellent'), ('good', 'good'), ('average', 'average')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(choices=[('new', 'new'), ('refurbished', 'refurbished')], default='new', max_length=20),
        ),
    ]
