# Generated by Django 4.2.4 on 2023-09-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_stock_variation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
