# Generated by Django 4.2.4 on 2023-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_price_variation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='refurbished_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished')], default='new', max_length=20),
        ),
    ]
