# Generated by Django 4.2.4 on 2023-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variation_refurbished_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='refurbished_quality',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_type',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('product_type', 'product_type')], default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
