# Generated by Django 4.2.4 on 2023-08-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_delete_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_img',
            new_name='category_images',
        ),
        migrations.AddField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
