# Generated by Django 4.2.4 on 2023-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
