# Generated by Django 4.2.4 on 2023-10-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_carousel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
