# Generated by Django 4.2.4 on 2023-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_coupon_appliedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discription',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
